# Generated by Django 3.0 on 2020-01-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200106_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizedProjectEditor',
        ),
    ]
