# Generated by Django 3.0 on 2020-01-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_authorizedprojecteditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_premium',
        ),
    ]
