# Generated by Django 3.0 on 2020-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_can_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rss_feed',
            field=models.URLField(blank=True),
        ),
    ]
