# Generated by Django 3.0 on 2020-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_rss_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rss_feed',
            field=models.URLField(blank=True, null=True),
        ),
    ]
