# Generated by Django 3.0 on 2020-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200109_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rss_feed',
            new_name='rss_feed_url',
        ),
        migrations.AddField(
            model_name='project',
            name='rss_feed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
