# Generated by Django 3.0 on 2020-01-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200109_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='rss_feed_text',
            new_name='rss_feed_item_data',
        ),
    ]
