# Generated by Django 3.0 on 2020-01-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200109_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rss_feed_item_data',
        ),
    ]
