# Generated by Django 3.0 on 2020-01-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_rss_feed_item_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rss_updates',
            field=models.BooleanField(default=False),
        ),
    ]
