# Generated by Django 3.0 on 2020-01-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='transcription_item_publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
