# Generated by Django 3.0 on 2019-12-18 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
