# Generated by Django 3.0 on 2019-12-20 01:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcriptions', '0002_transcription_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=255)),
                ('speaker_label', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='is_latest',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='job',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='transcription_text',
        ),
        migrations.AddField(
            model_name='project',
            name='can_edit',
            field=models.CharField(choices=[('edit', 'Edit Without Request'), ('request', 'Request Changes'), ('disabled', 'Cannot Edit')], default='edit', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transcription',
            name='language',
            field=models.CharField(choices=[('en-US', 'US English'), ('en-GB', 'British English'), ('es-US', 'US Spanish'), ('en-AU', 'Australian English'), ('fr-CA', 'Canadian Friend'), ('de-DE', 'German'), ('pt-BR', 'Brazilian Portuguese'), ('fr-FR', 'French'), ('it-IT', 'Italian'), ('ko-KR', 'Korean'), ('es-ES', 'Spanish'), ('en-IN', 'Indian English'), ('hi-IN', 'Indian Hindi'), ('ar-SA', 'Modern Standard Arabic'), ('ru-RU', 'Russian'), ('zh-CN', 'Mandarin Chinese')], default='en-US', max_length=250),
        ),
        migrations.AddField(
            model_name='transcription',
            name='settings_max_alternatives',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='transcription',
            name='settings_max_speaker_labels',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='transcription',
            name='settings_show_alternatives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='settings_show_speaker_labels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='transcription_key',
            field=models.SlugField(default='Transcription-<function now at 0x7fc07dc9da60>', max_length=255),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='status',
            field=models.CharField(choices=[('in_progress', 'IN PROGRESS'), ('failed', 'ERROR'), ('success', 'COMPLETED'), ('change_requested', 'PENDING_CHANGE')], max_length=128),
        ),
        migrations.CreateModel(
            name='TranscriptionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcription_text', models.TextField()),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.Transcription')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedTranscriptionEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.Transcription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedProjectEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionSpeaker',
            fields=[
                ('basespeaker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transcriptions.BaseSpeaker')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.Transcription')),
            ],
            bases=('transcriptions.basespeaker',),
        ),
        migrations.CreateModel(
            name='DefaultSpeakers',
            fields=[
                ('basespeaker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transcriptions.BaseSpeaker')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.Project')),
            ],
            bases=('transcriptions.basespeaker',),
        ),
    ]
