# Generated by Django 3.0 on 2020-01-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_transcriptiontext_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcription_text',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='TranscriptionText',
        ),
    ]
