# Generated by Django 3.0 on 2020-01-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_auto_20200121_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionedit',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='rejected', max_length=250),
            preserve_default=False,
        ),
    ]
