# Generated by Django 3.0 on 2020-01-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_auto_20200103_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'get_latest_by': ['-created_date'], 'ordering': ['-created_date']},
        ),
    ]
