# Generated by Django 3.0 on 2019-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_auto_20191219_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription_key',
            field=models.SlugField(default='Transcription-<function now at 0x7f5f25c60a60>', max_length=255),
        ),
    ]
