# Generated by Django 3.0 on 2020-01-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_transcriptionedit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionedit',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=250),
        ),
    ]
