# Generated by Django 3.0 on 2020-01-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0004_auto_20200106_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={},
        ),
    ]
