# Generated by Django 3.0 on 2020-01-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0004_auto_20200124_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionedit',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('overwitten', 'Overwritten'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=250),
        ),
    ]
