# Generated by Django 3.0 on 2019-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0004_auto_20191220_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='transcription_item_publish_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription_key',
            field=models.SlugField(default='Transcription-<function now at 0x7f5a7930ca60>', max_length=255),
        ),
    ]
