# Generated by Django 3.0 on 2019-12-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0005_auto_20191220_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription_key',
            field=models.SlugField(default='Transcription-<function now at 0x7f8a1503da60>', max_length=255),
        ),
    ]
