# Generated by Django 3.0 on 2020-03-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0006_auto_20200127_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='transcription_format',
            field=models.CharField(choices=[('MILLER', 'MILLER'), ('KENNEDY', 'KENNEDY')], default='MILLER', max_length=128),
        ),
    ]
