# Generated by Django 3.0 on 2020-01-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0006_auto_20200106_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={},
        ),
    ]
