# Generated by Django 3.0 on 2019-12-20 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0006_auto_20191220_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='transcription_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
