# Generated by Django 3.0 on 2020-01-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0007_auto_20200106_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptionspeaker',
            name='basespeaker_ptr',
        ),
        migrations.RemoveField(
            model_name='transcriptionspeaker',
            name='transcription',
        ),
        migrations.DeleteModel(
            name='AuthorizedTranscriptionEditor',
        ),
        migrations.DeleteModel(
            name='BaseSpeaker',
        ),
        migrations.DeleteModel(
            name='TranscriptionSpeaker',
        ),
    ]
