# Generated by Django 3.0 on 2020-01-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0008_auto_20200106_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='project',
        ),
    ]
