# Generated by Django 3.0 on 2020-01-07 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200106_2016'),
        ('transcriptions', '0009_remove_transcription_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
    ]
