# Generated by Django 3.0 on 2020-01-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0010_transcription_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['created_date', '-transcription_item_publish_date']},
        ),
    ]
