# Generated by Django 3.0 on 2020-01-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0011_auto_20200107_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='status',
            field=models.CharField(default='not_started', max_length=128),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
