# Generated by Django 3.0 on 2020-01-10 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0012_auto_20200109_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['-transcription_item_publish_date', 'created_date']},
        ),
        migrations.AlterField(
            model_name='transcription',
            name='settings_max_speaker_labels',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
