# Generated by Django 3.0 on 2020-01-14 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0014_transcriptionedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionedit',
            name='edited_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
