# Generated by Django 3.0 on 2020-01-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0015_auto_20200113_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionedit',
            name='transcription_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
